### ISSUE TITLE
Add FAQ: Backup/recovery of sealing key

### ISSUE THREAD

**Issue by Elexy** [bitnami/sealed-secrets#25]
Will you still be able to decrypt if you no longer have access to your cluster?

**Comment by anguslees** [comment]
No, the private key is only stored in the Secret managed by the controller (unless you have some other backup of your k8s objects).  There are no backdoors - without that private key, then you can't decrypt the SealedSecrets.   If you can't get to the Secret with the encryption key, and you also can't get to the decrypted versions of your Secrets live in the cluster, then you will need to regenerate new passwords for everything, seal them again with a new sealing key, etc.

If you _do_ want to make a backup of the encryption private key, it's easy to do from an account with suitable access and:
`kubectl get secret -n kube-system sealed-secrets-key -o yaml >master.key`
*This is the controller's public + private key and should be kept omg-safe!*

To restore from a backup after some disaster, just put that secret back before starting the controller - or if the controller was already started, replace the newly-created secret and restart the controller:
```
kubectl replace secret -n kube-system sealed-secrets-key master.key
kubectl delete pod -n kube-system -l name=sealed-secrets-controller
```

Thanks for the question - I'll add this to the README before closing this issue.

**Comment by Elexy** [comment]
@anguslees thanks for the explanation. That's what I thought.
