### ISSUE TITLE
Release does not include trp/crd manifests?

### ISSUE THREAD

**Issue by migmartri** [bitnami/sealed-secrets#59]
The following link obtained from the instructions in the readme returns a 404. Does the release include these files?

```
https://github.com/bitnami/sealed-secrets/releases/download/v0.4.0/sealedsecret-crd.yaml
```

**Comment by anguslees** [comment]
Existing/previous releases did not.  I cut a new release, which does.

Thanks for the nag, I let the gap between docs-update and release go too long :(
