### ISSUE TITLE
Upgrade k8s library?

### ISSUE THREAD

**Issue by bakins** [bitnami/sealed-secrets#69]
Currently, we have a custom command (like kubeseal) that has a lot of copy pasted code from this repo but we'd like to just use this as a library. Unfortunately, I quickly ran into issues as we need a newer version of the k8s client. k8s client seems to change package layout every release. Any interest in upgrading the k8s client used by sealed-secrets? I'm happy to do the work to make it happen.

**Comment by anguslees** [comment]
Hah! I've been working on exactly this over the last day or two.

Any particular client-go version you would like, or just "newer is better"?
